name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to v3

    - name: Setup Node.js (optional if your project needs Node)
      uses: actions/setup-node@v3  # Updated to v3
      with:
        node-version: '16'  # Node.js 16 is more stable or upgrade to 20 if needed

    - name: Build project
      run: |
        npm install
        npm run build

    - name: List files in output (debugging step)
      run: ls -la output

    - name: Create docs directory if not exists
      run: mkdir -p docs

    - name: Copy output to docs for GitHub Pages
      run: mv output/* docs/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs