name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # If necessary for your project, uncomment this block to set up Node.js
    # - name: Setup Node.js (optional)
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '14'

    # - name: Build project (if necessary)
    #   run: |
    #     # If you have a build process, run it here
    #     npm install
    #     npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output  # Publish only the output directory